### ISSUE TITLE
EAR doesn't work correctly

### ISSUE THREAD

**Issue by Krakenied** [PaperSpigot/Paper#11073]
### Expected behavior

Monsters shouldn't move, unless I'm in 1 block distance from them. On Spigot, it seems to be _much less reproducible_. Yeah, I know it sounds weird. I haven't noticed the issue to affect animals, however it may be an incorrect assumption.

### Observed/Actual behavior

Monsters move. It happens only sometimes - maybe after generation/spawn/chunk load?

### Steps/models to reproduce

```
    entity-activation-range:
      animals: 1
      monsters: 1
      raiders: 1
      misc: 1
      water: 1
      villagers: 1
      flying-monsters: 1
      wake-up-inactive:
        animals-max-per-tick: 0 # 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 0 # 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 0 # 4
        villagers-every: 600
        villagers-for: 100
        flying-monsters-max-per-tick: 0 # 8
        flying-monsters-every: 200
        flying-monsters-for: 100
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      tick-inactive-villagers: true
      ignore-spectators: false
```

### Plugin and Datapack List

n/a

### Paper version

```
> version
[13:20:26 INFO]: Checking version, please wait...
[13:20:26 INFO]: This server is running Paper version 1.21-63-master@2288e13 (2024-07-13T18:51:26Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-ea5f7d2 (MC: 1.21)
```

### Other

https://github.com/user-attachments/assets/38ef1b24-17e0-48c9-90ef-9f5d142333aa

Useless video details:
The Spigot version used: `CraftBukkit version 4263-Spigot-491f367-bed1e3f`
World seed: `6680692373436498971`
Coordinates: `-150 100 9750`
