### ISSUE TITLE
Obfuscation item feature does not work

### ISSUE THREAD

**Issue by Potothingi** [PaperSpigot/Paper#11225]
### Expected behavior

```
anticheat:
  obfuscation:
    items:
      hide-durability: true
      hide-itemmeta: true
      hide-itemmeta-with-visual-effects: true
```
This configuration exists in 1.21 Paper and I have enabled it, so the item meta should be hidden.

### Observed/Actual behavior

Item meta is not actually hidden. It's like I set a password on my phone but the phone isn't actually locked.
And this is like if I made my Facebook profile private and it shows as private but it is not actually private.

### Steps/models to reproduce

```
anticheat:
  obfuscation:
    items:
      hide-durability: true
      hide-itemmeta: true
      hide-itemmeta-with-visual-effects: true
```

### Plugin and Datapack List

Server Plugins (0):

There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
There are no more data packs available

### Paper version

This server is running Paper version 1.21-127-master@4e6a2a1 (2024-08-07T12:50:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
