### ISSUE TITLE
Minecraft server crashes and fills my logs

### ISSUE THREAD

**Issue by gragorther** [PaperSpigot/Paper#12003]
### Stack trace

https://mclo.gs/dqO62Wz

### Plugin and Datapack List

AdvancedTeleport, BetterChairs, BetterMessages, MiniMOTD, PingDisplay, Plan, ProtocolLib, SeeMore, ViaBackwards, ViaVersion

### Paper version

This server is running Paper version 1.21.4-121-main@88bbead (2025-01-22T20:05:15Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-118-73f7736 (MC: 1.21.4)

### Other

I use https://github.com/itzg/docker-minecraft-server and here is my docker compose file: 
```yaml
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-analytics.entryPoints=http
      - traefik.http.routers.http-analytics.rule=Host(`analytics.gregtech.eu`)
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.routers.http-analytics.middlewares=https_redirect
      - traefik.http.routers.https-analytics.entryPoints=https
      - traefik.http.routers.https-analytics.rule=Host(`analytics.gregtech.eu`)
      - traefik.http.routers.https-analytics.service=analytics
      - traefik.http.routers.https-analytics.tls=true
      - traefik.http.services.analytics.loadbalancer.server.port=8804
      - traefik.http.routers.https-analytics.tls.certResolver=le-ssl
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 32
      SIMULATION_DISTANCE: 32
      MEMORY: 7000M
      USE_AIKAR_FLAGS: true
    ports:
      - "25565:25565"
      - "45999:45999"
    volumes:
      - ./data:/data
    restart: always
volumes:
  mc-paper: {}
networks:
  default:
    name: traefik_access
    external: true

```
