### ISSUE TITLE
ItemMeta content incorrectly deserialized if inside shulker box

### ISSUE THREAD

**Issue by SkytAsul** [PaperSpigot/Paper#12086]
### Expected behavior

If I serialize a shulker box containing an item with complex ItemMeta (such as CustomModelData) in 1.21.1 and deserialize it in 1.21.4, I expect the ItemMeta to be unchanged (or rather, correctly upgraded if the data format has changed).

For instance, if this item is present in a shulker box in 1.21.1:
```yaml
  ==: org.bukkit.inventory.ItemStack
  v: 3955
  type: PAPER
  meta: 
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"text":"","extra":[{"text":"Custom Paper","italic":false}]}'
    custom-model-data: 42
```
I expect the shulker box in 1.21.4 to contain:
```yaml
item: 
  ==: org.bukkit.inventory.ItemStack
  v: 4189
  type: PAPER
  meta: 
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"text":"","extra":[{"text":"Custom Paper","italic":false}]}'
    custom-model-data: 
      ==: CustomModelData
      floats: 
      - 42.0
      flags: []
      strings: []
      colors: []
```

### Observed/Actual behavior

CustomModelData is incorrectly deserialized when contained in a shulker box. This error is printed in console (but it does not interrupt the stack):
```
[10:36:09 ERROR]: Tried to load invalid item: 'Not a map: 42 missed input: {"minecraft:custom_model_data":42}'
```
The shulker box contains
```yaml
  ==: org.bukkit.inventory.ItemStack
  v: 4189
  type: PAPER
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"text":"","extra":[{"text":"Custom Paper","italic":false}]}'
```

### Steps/models to reproduce

Here is an example plugin to reproduce: [serialization-error.tar.gz](https://github.com/user-attachments/files/18723910/serialization-error.tar.gz).

**On a 1.21.1 server:**
1. Give yourself a custom item with custommodeldata: `/give @a paper[custom_name='["",{"text":"Custom Paper","italic":false}]',custom_model_data=42]`
2. Save this item (hold it in your main hand and `/saveitem paper`).
3. Put it in a shulker box and serialize it (`/saveitem shulker`).

**On a 1.21.4 server:**
1. Load the paper item (`/loaditem paper`).
2. Serialize it again and see the _expected_ format.
3. Load the shulker item (`/loaditem shulker`). The error will appear.
4. Open the shulker box, take the paper item out and serialize it. You will see that the Custom Model Data has disappeared.

### Plugin and Datapack List

None, except the custom made one to show the issue.

### Paper version

Paper version 1.21.4-143-main@1a04e96 (2025-02-08T20:09:30Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Other

This issue also happens on Spigot. I filled in a bug report on their [JIRA](https://hub.spigotmc.org/jira/browse/SPIGOT-8006) and md_5 responded this:
> Problem is I don't know how to pass "v" from the item down into the ItemMeta and that's a pretty serious problem.

I hope it can help you.

I also found the issue #11077 that may have a relation with this one.
