### ISSUE TITLE
1.21.5 anti x-ray makes the client crash

### ISSUE THREAD

**Issue by SoSeDiK** [PaperSpigot/Paper#12396]
### Stack trace

Client crash log: https://mclo.gs/ISyq09d

### Plugin and Datapack List

Server startup log: https://mclo.gs/tFtTBJK
No plugins/datapacks

### Actions to reproduce (if known)

Fly around with anti x-ray enabled, experience client crashing

<details>
  <summary>Anti x-ray config used when the crash happened</summary>
  
```yml
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 1
    hidden-blocks:
    - coal_ore
    - deepslate_coal_ore
    - copper_ore
    - deepslate_copper_ore
    - raw_copper_block
    - diamond_ore
    - deepslate_diamond_ore
    - emerald_ore
    - deepslate_emerald_ore
    - gold_ore
    - deepslate_gold_ore
    - iron_ore
    - deepslate_iron_ore
    - raw_iron_block
    - lapis_ore
    - deepslate_lapis_ore
    - redstone_ore
    - deepslate_redstone_ore
    lava-obscures: true
    max-block-height: 64
    replacement-blocks:
    - stone
    - oak_planks
    - deepslate
    update-radius: 2
    use-permission: false
```
  
</details>

### Paper version

This server is running Paper version 1.21.5-DEV-update/1.21.5@e8eba88 (1970-01-01T00:00:00Z) (Implementing API version 1.21.5-R0.1-SNAPSHOT)
You are running the latest version

### Other

@lynxplay as requested ❤️
