### ISSUE TITLE
Per-world/paper.yml ticks-per.entity-spawns

### ISSUE THREAD

**Issue by hirata-estate** [PaperSpigot/Paper#6838]
### Is your feature request related to a problem?

I want my nether world's ticks-per.monster-spawns faster to replicate vanilla zombie piglin farm behavior, as they are much less efficient in my server; without negatively affecting the overworld.

### Describe the solution you'd like.

Like the spawn-limits category of bukkit.yml being in paper, just with ticks-per.spawns.
```
ticks-per:
  water-underground-creature-spawns: -1
  animal-spawns: -1
  monster-spawns: -1
  water-spawns: -1
  water-ambient-spawns: -1
  ambient-spawns: -1
  ```

### Describe alternatives you've considered.

Raising ticks-per.monster-spawns in bukkit.yml. This has the effect of causing lag for the overworld as opposed to optimized values, instead of just helping with the nether spawns.
