### ISSUE TITLE
Other players' Soul Speed Particles not visible (hide-unnecessary-itemmeta issue)

### ISSUE THREAD

**Issue by Pantera07** [PaperSpigot/Paper#7238]
### Expected behavior

I can see other players' Soul Speed Particles.

### Observed/Actual behavior

I can't see other players' Soul Speed Particles. (hide-unnecessary-itemmeta issue)

### Steps/models to reproduce

paper.yml
```
    anticheat:
      obfuscation:
        items:
          hide-itemmeta: true
          hide-durability: true
```
Observe another player wearing Soul Speed enchanted shoes walking on Soul Sand.

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-120 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3a43821)
