### ISSUE TITLE
Make feature-seeds generate for all based on world-type.

### ISSUE THREAD

**Issue by hirata-estate** [PaperSpigot/Paper#7285]
### Is your feature request related to a problem?

```
    feature-seeds:
      generate-random-seeds-for-all: false
```
Setting generate-random-seeds-for-all to true will make **all worlds** have different seeds for everything possible.

For the nether and the end, seeds like "azalea_tree" and "sea_pickle" are not necessary.
This also applies to the overworld, e.x. "ore_soul_sand" and "chorus_plant"

This results in a rather unnecessarily large configuration filled with seeds, and difficulties are more apparent when wanting to do a quick change in the configuration, only to have to scroll through so much before finding the config you need.

### Describe the solution you'd like.

Make setting feature-seeds.generate-random-seeds-for-all to true different per world type.
e.g. setting it to true will result in end dimension worlds only have seeds necessary for that specific dimension.

### Describe alternatives you've considered.

You can currently enable the configuration, restart the server to it generates the seeds in the config, then turn it back off & cherry pick or remove the seeds for each specific world.

### Other

I might've removed two or three seeds on accident, I didn't scan through the seeds carefully.
But, the feature-seeds section to the end dimension could be compressed to more of this size.
```
  world_the_end:
    feature-seeds:
      end_gateway_delayed: 190505040180903011
      end_gateway_return: 190505040180903011
      delta: 190505040180903011
      chorus_plant: 190505040180903011
      end_island: 190505040180903011
      end_spike: 190505040180903011
      void_start_platform: 190505040180903011
```

**Comment by BillyGalbreath** [comment]
It's already in the `world-settings` section. Just leave it `false` for `default` (all worlds) and enable it only in the worlds you want:

```yaml
world-settings:
  default:
    feature-seeds:
      generate-random-seeds-for-all: false
  world:
    feature-seeds:
      generate-random-seeds-for-all: true
```
