### ISSUE TITLE
1.18 anti-xray nether/theend loads very slowly

### ISSUE THREAD

**Issue by zz2423257** [PaperSpigot/Paper#7843]
### Description of issue

1.18 anti-xray After enabling it, my nether/theend loads very slowly

### Server config files

```
paper
# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
#
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
#
# Discord: https://discord.gg/papermc
# IRC: #paper @ irc.esper.net ( https://webchat.esper.net/?channels=paper ) 
# Website: https://papermc.io/ 
# Docs: https://docs.papermc.io/ 

use-display-name-in-quit-message: false
verbose: false
config-version: 27
settings:
  use-dimension-type-for-custom-spawners: false
  fix-target-selector-tag-completion: true
  time-command-affects-all-worlds: false
  send-full-pos-for-hard-colliding-entities: true
  lag-compensate-block-breaking: true
  log-player-ip-addresses: true
  fix-entity-position-desync: true
  track-plugin-scoreboards: false
  enable-player-collisions: true
  save-empty-scoreboard-teams: false
  chunk-tasks-per-tick: 1000
  max-joins-per-tick: 3
  region-file-cache-size: 256
  incoming-packet-spam-threshold: 300
  suggest-player-names-when-null-tab-completions: true
  console-has-all-permissions: false
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  bungee-online-mode: true
  load-permissions-yml-before-plugins: true
  use-alternative-luck-formula: false
  unsupported-settings:
    perform-username-validation: true
    allow-permanent-block-break-exploits: false
    allow-piston-duplication: false
    allow-headless-pistons: false
    allow-permanent-block-break-exploits-readme: This setting controls if players
      should be able to break bedrock, end portals and other intended to be permanent
      blocks.
    allow-piston-duplication-readme: This setting controls if player should be able
      to use TNT duplication, but this also allows duplicating carpet, rails and potentially
      other items
    allow-headless-pistons-readme: This setting controls if players should be able
      to create headless pistons.
  spam-limiter:
    recipe-spam-increment: 1
    recipe-spam-limit: 20
    tab-spam-increment: 1
    tab-spam-limit: 500
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  async-chunks:
    threads: -1
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
  velocity-support:
    enabled: false
    online-mode: false
    secret: ''
  console:
    enable-brigadier-highlighting: true
    enable-brigadier-completions: true
  item-validation:
    display-name: 8192
    loc-name: 8192
    lore-line: 8192
    book:
      title: 8192
      author: 8192
      page: 16384
  use-display-name-in-quit-message: false
  chunk-loading:
    player-max-chunk-load-rate: -1.0
    min-load-radius: 2
    max-concurrent-sends: 2
    autoconfig-send-distance: true
    target-player-chunk-send-rate: 100.0
    global-max-chunk-send-rate: -1.0
    enable-frustum-priority: false
    global-max-chunk-load-rate: -1.0
    player-max-concurrent-loads: 20.0
    global-max-concurrent-loads: 500.0
  loggers:
    use-rgb-for-named-text-colors: true
    deobfuscate-stacktraces: true
  packet-limiter:
    kick-message: '&c發送的封包過多，建議使用正常的登入器進行遊玩'
    limits:
      all:
        interval: 7.0
        max-packet-rate: 500.0
      PacketPlayInAutoRecipe:
        interval: 4.0
        max-packet-rate: 5.0
        action: DROP
timings:
  really-enabled: true
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  - settings.velocity-support.secret
  - settings.seed
  - settings.seed.dungeon
  - settings.seed.end-spike
  - server-ip
  - worldgen.seeds.populator
  - web-services.token
  history-interval: 300
  history-length: 3600
  server-name: 世紀
  url: https://timings.aikar.co
messages:
  no-permission: '&6系統 &7» &c你沒有權限'
  kick:
    authentication-servers-down: ''
    flying-player: 伺服器沒有開啟飛行
    flying-vehicle: 伺服器沒有開啟飛行
    connection-throttle: 連接受阻！ 請等待，然後重新連接
world-settings:
  default:
    slime-spawn-height:
      swamp-biome:
        maximum: 70.0
        minimum: 50.0
      slime-chunk:
        maximum: 40.0
    wateranimal-spawn-height:
      maximum: default
      minimum: default
    monster-spawn-max-light-level: -1
    anticheat:
      obfuscation:
        items:
          hide-itemmeta: true
          hide-durability: true
    allow-player-cramming-damage: false
    map-item-frame-cursor-update-interval: 10
    show-sign-click-command-failure-msgs-to-player: false
    split-overstacked-loot: true
    piglins-guard-chests: true
    seed-based-feature-search-loads-chunks: false
    fix-items-merging-through-walls: false
    map-item-frame-cursor-limit: 128
    allow-using-signs-inside-spawn-protection: false
    fix-wither-targeting-bug: false
    update-pathfinding-on-block-update: true
    ender-dragons-death-always-places-dragon-egg: false
    only-players-collide: false
    allow-vehicle-collisions: true
    max-leash-distance: 10.0
    portal-search-vanilla-dimension-scaling: true
    fix-climbing-bypassing-cramming-rule: false
    seed-based-feature-search: true
    should-remove-dragon: false
    skeleton-horse-thunder-spawn-chance: 1.0E-4
    keep-spawn-loaded: true
    disable-thunder: false
    disable-ice-and-snow: false
    grass-spread-tick-rate: 4
    allow-non-player-entities-on-scoreboards: false
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    container-update-tick-rate: 1
    armor-stands-do-collision-entity-lookups: true
    zombies-target-turtle-eggs: true
    zombie-villager-infection-chance: -1.0
    spawner-nerfed-mobs-should-jump: false
    entities-target-with-follow-range: false
    water-over-lava-flow-speed: 5
    nether-ceiling-void-damage-height: 0
    portal-search-radius: 128
    portal-create-radius: 16
    keep-spawn-loaded-range: 10
    baby-zombie-movement-modifier: 0.5
    count-all-mobs-for-spawning: false
    delay-chunk-unloads-by: 10s
    use-vanilla-world-scoreboard-name-coloring: false
    prevent-moving-into-unloaded-chunks: false
    max-auto-save-chunks-per-tick: 6
    disable-creeper-lingering-effect: false
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    filter-nbt-data-from-spawn-eggs-and-related: true
    mob-spawner-tick-rate: 2
    prevent-tnt-from-moving-in-water: false
    iron-golems-can-spawn-in-air: false
    non-player-arrow-despawn-rate: -1
    creative-arrow-despawn-rate: -1
    disable-teleportation-suffocation-check: false
    armor-stands-tick: true
    light-queue-size: 20
    all-chunks-are-slime-chunks: false
    auto-save-interval: -1
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: true
    per-player-mob-spawns: true
    optimize-explosions: true
    fixed-chunk-inhabited-time: -1
    remove-corrupt-tile-entities: false
    experience-merge-max-value: -1
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    max-entity-collisions: 8
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    game-mechanics:
      disable-mob-spawner-spawn-egg-transformation: false
      fix-curing-zombie-villager-discount-exploit: true
      disable-end-credits: false
      shield-blocking-delay: 5
      disable-sprint-interruption-on-attack: false
      disable-chest-cat-detection: true
      nerf-pigmen-from-nether-portals: false
      disable-player-crits: false
      disable-relative-projectile-velocity: false
      disable-unloaded-chunk-enderpearl-exploit: true
      scan-for-legacy-ender-dragon: true
      disable-pillager-patrols: false
      pillager-patrols:
        spawn-chance: 0.2
        spawn-delay:
          per-player: false
          ticks: 12000
        start:
          per-player: false
          day: 5
    viewdistances:
      no-tick-view-distance: -1
    anti-xray:
      enabled: true
      use-permission: false
      lava-obscures: false
      engine-mode: 1
      max-block-height: 128
      update-radius: 1
      hidden-blocks:
      - copper_ore
      - deepslate_copper_ore
      - gold_ore
      - deepslate_gold_ore
      - iron_ore
      - deepslate_iron_ore
      - coal_ore
      - deepslate_coal_ore
      - lapis_ore
      - deepslate_lapis_ore
      - diamond_ore
      - deepslate_diamond_ore
      - redstone_ore
      - deepslate_redstone_ore
      - emerald_ore
      - deepslate_emerald_ore
      replacement-blocks:
      - stone
      - deepslate
    lightning-strike-distance-limit:
      sound: -1
      impact-sound: -1
      flash: -1
    hopper:
      ignore-occluding-blocks: true
      cooldown-when-full: true
      disable-move-event: true
    squid-spawn-height:
      maximum: 0.0
    generator-settings:
      flat-bedrock: false
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    max-growth-height:
      cactus: 3
      reeds: 3
      bamboo:
        max: 16
        min: 11
    despawn-ranges:
      axolotls:
        soft: 32
        hard: 128
      monster:
        soft: 32
        hard: 128
      creature:
        soft: 32
        hard: 128
      ambient:
        soft: 32
        hard: 128
      underground_water_creature:
        soft: 32
        hard: 128
      water_creature:
        soft: 32
        hard: 128
      water_ambient:
        soft: 32
        hard: 64
      misc:
        soft: 32
        hard: 128
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    alt-item-despawn-rate:
      enabled: false
      items:
        cobblestone: 300
    wandering-trader:
      spawn-minute-length: 1200
      spawn-day-length: 24000
      spawn-chance-failure-increment: 25
      spawn-chance-min: 25
      spawn-chance-max: 50
    mobs-can-always-pick-up-loot:
      zombies: false
      skeletons: false
    door-breaking-difficulty:
      zombie_villager:
      - HARD
      husk:
      - HARD
      zombified_piglin:
      - HARD
      zombie:
      - HARD
      vindicator:
      - NORMAL
      - HARD
    entity-per-chunk-save-limit:
      fireball: -1
      small_fireball: -1
      experience_orb: -1
      snowball: 20
      ender_pearl: 20
      arrow: 20
    unsupported-settings:
      fix-invulnerable-end-crystal-exploit: true
    spawn-limits:
      axolotls: -1
      monster: -1
      creature: -1
      underground_water_creature: -1
      water_creature: -1
      water_ambient: -1
      ambient: -1
    feature-seeds:
      generate-random-seeds-for-all: false
    mob-effects:
      undead-immune-to-certain-effects: true
      spiders-immune-to-poison-effect: true
      immune-to-wither-effect:
        wither: true
        wither-skeleton: true
    tick-rates:
      sensor:
        villager:
          secondarypoisensor: 40
      behavior:
        villager:
          validatenearbypoi: -1
    redstone-implementation: eigencraft
  world_nether:
    anti-xray:
      max-block-height: 128
      hidden-blocks:
      - ancient_debris
      - nether_gold_ore
      - nether_quartz_ore
  world_the_end:
    anti-xray:
      enabled: false

```

### Paper version
This server is running Paper version git-Paper-339 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9b492cf)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-333 (MC: 1.18.2)
