### ISSUE TITLE
config upgrades inconsistent

### ISSUE THREAD

**Issue by Netherwhal** [PaperSpigot/Paper#8055]
### Expected behavior

When upgrading from 1.18 to 1.19 config files should look like described in https://docs.papermc.io/paper/cat/admin/reference

### Observed/Actual behavior

A couple of examples:

not an integer:

```
non-player-arrow-despawn-rate: '1'
```

completely non-existent config-keys and values:

```
misc:
  disable-end-credits: false
  disable-relative-projectile-velocity: false
  disable-sprint-interruption-on-attack: false
  light-queue-size: 20
  max-leash-distance: 10.0
  redstone-implementation: ALTERNATE_CURRENT
  shield-blocking-delay: 5
  show-sign-click-command-failure-msgs-to-player: false
  update-pathfinding-on-block-update: false
```

### Steps/models to reproduce

Upgrade from 1.18 to 1.19

### Plugin and Datapack List

none

### Paper version

```
> version
[09:28:26 INFO]: Checking version, please wait...
[09:28:27 INFO]: This server is running Paper version git-Paper-39 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 37afe98)
You are running the latest version
Previous version: git-Paper-386 (MC: 1.18.2)
```
