### ISSUE TITLE
Provide API for datastore configuration

### ISSUE THREAD

**Issue by NeumimTo** [PaperSpigot/Paper#8064]
### Is your feature request related to a problem?

Usually every bigger server is running at least two or more plugins that connect to same database. The more plugins we install the more this configuration become scattered all over place. 

If we change the database (migrate to a new host, change password, change uname) we have to go through dozens of plugin configuration files and find all references to database configuration and update it one by one

To clean this up spigot could provide a configuration api that other plugins could use to fetch things like connection string, passwords, table prefixes etc.

### Describe the solution you'd like.

Unified api/configuration that plugins could use to read stuff like jdbc connection from. 

Some notes:
- The configuration should be something simple that takes very little time for plugin devs to implement, and can be generally implemented everywhere.
- Im not asking for paper to provide things like unified connection pooling library, the jdbc driver for specific databse - thats up to the plugins
- Ability to have per-plugin configuration with fallback to default configuration

Examples by code: 

paper.yml

```
   datasources:
      default:
            host: localhost
            port: 5432
            database: minecraft
            connection-pool-size: 2
            password: 0pass1234
      towny:
             table-prefix: towny
      factions:
           host: something.aws.com
           port: 5431
           database: minecraftion
           connection-pool-size: 10

```
pseudocode for plugins

      var obj = Bukkit.getServer().getDatasourceConfiguration().readDataForPlugin(Towny.class);
     obj.getHost() // configuration section datasource.towny has no host key, therefore it would fallback to  datasource.default
     
      var obj = Bukkit.getServer().getDatasourceConfiguration().readDataForPlugin(Factions.class);
     obj,getHost() // configureation section datasource.faction has host key, therefore it would return url "something.aws.com"
                          
      var obj = Bukkit.getServer().getDatasourceConfiguration().readDataForPlugin(SomeOtherPlugin.class);
     obj,getHost() // configureation section datasource.someotherplugin do not exists, therefore this fallbacks to "datasource.default"
     
```

     

### Describe alternatives you've considered.

>Describe alternatives you've considered.
none (mandatory field)

### Other

_No response_
