### ISSUE TITLE
anticheat.obfuscation.items adding functionality

### ISSUE THREAD

**Issue by Ne0shka** [PaperSpigot/Paper#8256]
### Is your feature request related to a problem?

At the moment, there are 2 options that help against cheating clients, these are `anticheat.obfuscation.items.hide-durability` and `anticheat.obfuscation.items.hide-itemmeta`. However, as indicated in the documentation itself, this breaks the resourcepacks based on these values. And this limits the administrators who introduce such resourcepacks. Therefore, the idea arose to supplement this functionality.

### Describe the solution you'd like.

For the `hide-durability` parameter, enter a list of values that will still be sent to the client. For example: `[0, 100, 200]`. When the strength value reaches one of the list values or less, the value from the list is sent to the client. Thus, the client does not know about the exact strength value, but this does not break the resourcepacks.

For the `hide-itemmeta` parameter, enter a list of values that will ignore the boolean value and will be sent to the client anyway. Thus, the client may not know about enchants and other information, but the resource packs will also partially not break.

### Describe alternatives you've considered.

I don't know about alternatives

### Other

```
anticheat:
  obfuscation:
    items:
      hide-durability:
        enable: true
        ignore-values: []
      hide-itemmeta:
        enable: true
        ignore-values: []
```
