### ISSUE TITLE
Separate height and width in Simulate-Distance and View-Distance

### ISSUE THREAD

**Issue by Euphillya** [PaperSpigot/Paper#8375]
### Is your feature request related to a problem?

In many game modes, loaded chunks are often useless.

### Describe the solution you'd like.

Hello,

I have a suggestion for a configuration for the Distance Simulation and View Distance.

On some servers, loading the height and width can be separated depending on the gameplay and can increase performance.
For example, on a Skyblock, we favour height over width and in a PVP arena, we favour width over height.

I don't know if this is feasible, but I'd rather submit the idea.

Good day to you.

### Describe alternatives you've considered.

Add a configuration like :

```yml
world :
   simulation_distance :
      height : default
      weight : default
   view_distance:
      height : default
      weight : default
```
