### ISSUE TITLE
Anti-Xray engine-mode: 2 configurable # (or %) of blocks replaced

### ISSUE THREAD

**Issue by EvModder** [PaperSpigot/Paper#8764]
### Is your feature request related to a problem?

One of the drawbacks [as noted in Paper's docs](https://docs.papermc.io/paper/anti-xray) with `engine-mode: 2` is the increased computation cost for server/client.

### Describe the solution you'd like.

A really nice feature would be a setting (either a %, or a # limit) for how many blocks get replaced in `engine-mode: 2`, allowing for the server impact to be adjusted as needed.  Through testing (via plugin with packet intercept), it seems that even as low as replacing 2% of stone and air with ores is enough to effectively neutralize Xray.

### Describe alternatives you've considered.

Currently the alternatives are to use `engine-mode: 1` (less effective), use a plugin (likely more costly than a paper-native solution), or to disable Anti-Xray.

**Comment by KioProject123** [comment]
Currently there is an alternative that just needs to add enough air.
I've been using it for a long time and it works and saves a lot of network traffic.
Of course, it would be better to configure the ratio of blocks more conveniently.
```
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 2
    hidden-blocks:
    - cave_air
    - cave_air
    - cave_air
    - cave_air
    - cave_air
   ...
```
