### ISSUE TITLE
Lava obscures does not use replacement blocks defined in world config

### ISSUE THREAD

**Issue by davidjpfeiffer** [PaperSpigot/Paper#9067]
### Is your feature request related to a problem?

The anti xray config for each world includes a lava-obscures value which indicates whether or not blocks adjacent to lava should be obscured by the anti xray. This works, but instead of obscuring blocks adjacent to lava with the replacement-blocks Paper instead uses the replacement blocks present in the default config.

### Describe the solution you'd like.

When `lava-obscures` is set to `true` I would like blocks adjacent to lava to be replaced with one of the blocks defined in the `replacement-blocks` config value list.

### Describe alternatives you've considered.

None.

### Other

Here is the config I am using for The Nether world:

```
_version: 30
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 2
    hidden-blocks:
    - ancient_debris
    - bone_block
    - glowstone
    - magma_block
    - nether_bricks
    - nether_gold_ore
    - nether_quartz_ore
    - polished_blackstone_bricks
    lava-obscures: true
    max-block-height: 128
    replacement-blocks:
    - netherrack
    update-radius: 2
    use-permission: false
```
