### ISSUE TITLE
Plugin dependencies of paper plugins fail to load as of build 503

### ISSUE THREAD

**Issue by WiIIiam278** [PaperSpigot/Paper#9114]
### Expected behavior

The changes introduced in https://github.com/PaperMC/Paper/pull/9068 break the loading of plugin dependencies for paper plugins.

I have a [plugin](https://modrinth.com/plugin/huskhomes/version/4.1.1) that defines a paper-plugin.yml file which contains several dependencies.

<details>
<summary>paper-plugin.yml snippet</summary>

```yaml
dependencies:
  - name: Vault
    required: false
  - name: RedisEconomy
    required: false
  - name: PlaceholderAPI
    required: false
  - name: dynmap
    required: false
  - name: BlueMap
    required: false
  - name: Plan
    required: false
  - name: Pl3xMap
    required: false
load-before:
  - name: Essentials
load-after:
  - name: Vault
  - name: RedisEconomy
  - name: PlaceholderAPI
  - name: dynmap
  - name: BlueMap
  - name: Plan
  - name: Pl3xMap
```
</details>

On builds 502 and below, on servers with (for example) Dynmap installed alongside my plugin, the hook I wrote for Dynmap loads fine.

### Observed/Actual behavior

On builds 503 and up, Dynmap's API is not added to the classpath of my plugin and throws a ClassNotFound exception when trying to load

<details>
<summary>stack trace provided by an end user</summary>

![image](https://user-images.githubusercontent.com/31187453/230875005-4a141eae-c3ab-4045-883f-9c71e534c566.png)
</details>

The same is true with other plugin API hooks written for my plugin. Note that I wrote a custom loader for my plugin that loads some libraries; this is unrelated and these libraries load fine, but for reference [here's the class](https://github.com/WiIIiam278/HuskHomes2/blob/master/paper/src/main/java/net/william278/huskhomes/PaperHuskHomesLoader.java).

### Steps/models to reproduce

Download HuskHomes v4.1.1 https://modrinth.com/plugin/huskhomes/version/4.1.1
Download Dynmap
Install HuskHomes on your Paper (build 503+) server
Ensure HuskHomes' dynmap hook is turned ON in its config
Observe as it throws the exception

### Plugin and Datapack List

HuskHomes
Dynmap

### Paper version

build 506-8be7a60
