### ISSUE TITLE
Too much plugin messages prevent players from joining other server

### ISSUE THREAD

**Issue by PapiCapi** [PaperSpigot/Paper#9207]
### Expected behavior

The player shouldn't be kicked when trying to join the server.

### Observed/Actual behavior

If on a server (serverA) a plugin sends multiple plugin messages (around 4200) though a BungeeCord channel, then, if a player tries to join a server with no players (serverB) he will be "Kicked for exceeding packet rate limit".

![Screenshot_1](https://github.com/PaperMC/Paper/assets/49530141/463e99ff-7f01-4160-be82-f859dcef5c1c)

I also tried to modify the packet limiter in the paper config but nothing changed.
Here is what i tried : 

```
packet-limiter:
  all-packets:
    action: KICK
    interval: 7.0
    max-packet-rate: 500.0
  kick-message: <red><lang:disconnect.exceeded_packet_rate>
  overrides:
    ServerboundCustomPayloadPacket:
      action: DROP
      interval: 7.0
      max-packet-rate: 500.0
    ServerboundPlaceRecipePacket:
      action: DROP
      interval: 4.0
      max-packet-rate: 5.0
```

### Steps/models to reproduce

- Create 2 paper servers (serverA and serverB) and 1 waterfall / bungee server.
- Make sure that no one is on the serverB
- Connect to the serverA and send multiple plugin messages using a plugin
- Try to connect to serverB
-> You will be kicked for exceeding packet rate limit.

Here is my class allowing to send the plugin messages : https://pastebin.com/AqeP11XV 

### Plugin and Datapack List

Plugins (4): ProtocolLib, StaffCore (the plugin sending plugin messages), ViaBackwards, ViaVersion

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

This server is running Paper version git-Paper-393 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: afa16e6)
You are 55 version(s) behind
Download the new version at: https://papermc.io/downloads

I used an old version but i was able to reproduce this issue with the latest builds.

### Other

I used this class to see how many packets were receved : https://pastebin.com/U6Gx72F4 
I suggest creating the test plugin with both of the class provided and set this plugin on serverA and serverB so that you can see the limit of packets sent. For me, it was 4192 packets.
