### ISSUE TITLE
Migrating from 1.8 to 1.20.1 does not remove some settings

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9357]
### Expected behavior

Remove settings that no longer exist

### Observed/Actual behavior

Some settings are not removed

### Steps/models to reproduce

Upgrade from Paper 1.8 to Paper 1.20.1

### Plugin and Datapack List

Tested without plugins and 1.8 does not support datapacks

### Paper version

> version
[22:47:38 INFO]: Checking version, please wait...
[22:47:39 INFO]: This server is running Paper version git-Paper-31 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a226f44)
You are running the latest version

### Other

Settings that are not removed:

PaperGlobalConfig:

```
stackable-buckets:
  lava: false
  water: false
  milk: false
data-value-allowed-items: []
effect-modifiers:
  strength: 1.3
  weakness: -0.5
 ```

 PaperWorldConfig:
 
```
 lava-flow-speed:
  nether: 10
  normal: 30
 fast-drain:
  lava: false
  water: false
falling-blocks-collide-with-signs: false
load-chunks:
  enderpearls: false
  falling-blocks: false
  tnt-entities: false
tick-next-tick-list-cap: 10000
tick-next-tick-list-cap-ignores-redstone: false
remove-unloaded:
  enderpearls: true
  falling-blocks: true
  tnt-entities: true
player-exhaustion:
  block-break: 0.02500000037252903
  swimming: 0.014999999664723873
```
