### ISSUE TITLE
[Feature Request] Hide Player Health

### ISSUE THREAD

**Issue by Potothingi** [PaperSpigot/Paper#9447]
### Is your feature request related to a problem?

paper can hide an item's durability and itemmeta, but it cannot hide the player's health.

### Describe the solution you'd like.

```
anticheat:
  obfuscation:
    items:
      hide-durability: true
      hide-itemmeta: true
      hide-itemmeta-with-visual-effects: true
    player:
      hide-health: true ☜☜☜
```
It would be nice to have an option to hide the player's health.

### Describe alternatives you've considered.

I haven't found a plugin that hides the player's health.
