### ISSUE TITLE
[Feature Request] Configuration to prevent entities from using portals

### ISSUE THREAD

**Issue by Potothingi** [PaperSpigot/Paper#9582]
### Is your feature request related to a problem?

Ghasts cause server lag spikes when using nether portals.
https://github.com/PaperMC/Paper/issues/9173

### Describe the solution you'd like.

It would be nice if there was a configuration to prevent specified entities from using the portal.
```
entities:
  behavior:
    prevent-entity-portal-use:
    - ghast
```

### Describe alternatives you've considered.

I couldn't find any plugin that does this. It would be great if Paper could do this to avoid portal lag spikes.
